# Generated by Django 2.1.8 on 2019-08-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
