# Generated by Django 2.1.8 on 2019-10-16 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20190910_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, default=product.models.increment_invoice_number, max_length=500, null=True, validators=[django.core.validators.RegexValidator(code='Number is invalide', message='Produce number must be Alphanumeric', regex='^[a-zA-Z0-9]*$')])),
                ('customer_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default=0)),
                ('activation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.Product')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
