# Generated by Django 2.1.8 on 2019-10-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='address',
            field=models.TextField(default='pp'),
            preserve_default=False,
        ),
    ]
