# Generated by Django 2.1.8 on 2019-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_orderproduct_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
