# Generated by Django 2.1.8 on 2019-10-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_orderproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_image',
        ),
    ]
