# Generated by Django 2.1.8 on 2019-10-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_promotion_promotion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_as_percentag',
        ),
    ]
